title: Six-legged livestock
author: Thomas Klammsteiner
affiliation: Department of Microbiology, University of Innsbruck
address: Technikerstraße 25d
location: 6020 Innsbruck, AT
email: fromwastetofeed@outlook.com
phone: +43 (0)512 507 51322